# Generated by Django 3.1.7 on 2021-09-18 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geolocapp', '0002_merchandise'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Merchandise',
        ),
    ]
